.TH GDK-PIXBUF-PIXDATA "1" "November 2013" "gdk-pixbuf-pixdata" "User Commands"
.SH NAME
gdk-pixbuf-pixdata \- GDK Pixbuf library
.SH SYNOPSIS
.B gdk-pixbuf-pixdata
[\fIoptions\fR] [\fIinput-file\fR] [\fIoutput-file\fR]
.SH DESCRIPTION
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message
.TP
\fB\-v\fR, \fB\-\-version\fR
print version information
.TP
\fB\-\-g\-fatal\-warnings\fR
make warnings fatal (abort)
.PP
gdk\-pixbuf\-pixdata comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of gdk\-pixbuf\-pixdata under the terms of
the GNU Lesser General Public License which can be found in the
gdk\-pixbuf source package. Sources, examples and contact
information are available at http://www.gtk.org
